#services:
#  postgres:
#    container_name: postgres_container
#    image: postgres
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: ecommerce
#      PGDATA: /data/postgres
#      POSTGRES_INITDB_ARGS: "--lc-time=Asia/Kolkata"
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - "5432:5000"
#    networks:
#      - postgres
#    restart: unless-stopped
#  pgadmin:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    restart: unless-stopped
#networks:
#  postgres:
#    driver: bridge
#volumes:
#  postgres:
#  pgadmin:


#services:
#  postgres:
#    container_name: postgres_container
#    image: postgres:14
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: ecommerce
#      PGDATA: /data/postgres
#    volumes:
#      - postgres:/data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - ecommerce
#    restart: unless-stopped
#
#  product-service:
#    build: ./product-service
#    container_name: product_service_container
#    ports:
#      - "8081:8081"
#    networks:
#      - ecommerce
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#
#  user-service:
#    build: ./user-service
#    container_name: user_service_container
#    ports:
#      - "8082:8082"
#    networks:
#      - ecommerce
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#
#  order-service:
#    build: ./order-service
#    container_name: order_service_container
#    ports:
#      - "8083:8083"
#    networks:
#      - ecommerce
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#
#networks:
#  ecommerce:
#    driver: bridge
#
#volumes:
#  postgres:
#    driver: local
#  pgadmin:
#    driver: local
#



services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres


      POSTGRES_DB: ecommerce
      PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: "--lc-time=Asia/Kolkata"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@demo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - my-network
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:

networks:
  my-network: