spring:
  application:
    name: Gate-way
    cloud:
      gateway:
        routes:
          - id: product-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/product/**
          - id: user-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/user/**
          - id: order-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/order/**,/api/cart/**

server:
  port: 8080
